### ISSUE TITLE
Apply [Template] attributes to SVG element ctors

### ISSUE THREAD

**Issue by AndreyChechel** [Retyped/Retyped#42]
1. DOM API defines constructors for SVG elements, however, similarly to regular HTML elements they can't be invoked directly. We can apply proper **[Template]** attributes to constructors in order to simplify instantiation. E.g. a constructor for **SVGImageElement** should look like this:

```cs
public sealed class SVGImageElement : SVGGraphicsElement, SVGURIReference.Interface
{
   [Bridge.Template("document.createElementNS(\"http://www.w3.org/2000/svg\", \"image\")")]
   public extern SVGImageElement();

   // ...
}
```

2. Some of the SVG classes already have templates applied and configured for invoking `document.createElement( .. )` function. They should be corrected to use `createElementNS(..)` instead.

**Found in:**
- [lib.dom.d.ts](https://github.com/Microsoft/TypeScript/blob/d2fd137d882b66a1f1dd73be5fd3570c4654fa85/lib/lib.dom.d.ts#L10300)

## C# sample

https://deck.net/cf55e173a8860235221c7257fd05e4f3

```cs
public class Program
{
    public static void Main()
    {
        var svg = new Retyped.dom.SVGAElement();
        
        Console.WriteLine("SVGAElement was created successfully.");
    }
}
```

## Actual

```js
System.Exception: TypeError: Illegal constructor
    at Function.Main (https://deck.net/RunHandler.ashx?h=-1957374861:9:23)
    at https://deck.net/resources/js/bridge/bridge.min.js?16.6.1:7:39403
    at HTMLDocument.i (https://deck.net/resources/js/bridge/bridge.min.js?16.6.1:7:5182)
    at i (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27151)
    at Object.add [as done] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:29515)
    at new n.fn.init (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:24945)
    at n (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:405)
    at Object.ready (https://deck.net/resources/js/bridge/bridge.min.js?16.6.1:7:5245)
    at https://deck.net/resources/js/bridge/bridge.min.js?16.6.1:7:39382
```

## Expected

Console output:
```
SVGAImageElement was created successfully.
```

## See also
- https://forums.bridge.net/forum/community/help/5099-recommendations-for-creating-strongly-typed-svg-elements

**Comment by AndreyChechel** [comment]
An update package [Retyped.dom.2.3.6589](https://www.nuget.org/packages/Retyped.dom/2.3.6589) has been pushed to NuGet.
